---
title: "project_pt2"
output: pdf_document
date: "2023-04-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(haven)
library(ggthemes)
library(statar) 
library(tidyquant)
library(purrr)
library(sandwich)
library(lmtest)
library(tidyr)
library(knitr)
library(kableExtra)
library(webshot)
library(magick)
library(stargazer)
library(fixest)
atlas <- read_dta("atlas.dta")
view(atlas)
```



```{r}
#Initial data wrangling 
#Subsetting for Wake County
wake_co <- atlas %>% subset(state == "37" & county == "183") 
view(wake_co)
#How many census tracts in Wake County?
length(unique(wake_co$tract))

#Subsetting for my neighborhood (Fuquay-Varina, Holly Springs, and Willow Spring)
fuquay <- wake_co |> subset(str_detect(tract_name, "Fuquay Varina") | str_detect(tract_name, "Holly Springs") |tract == "53110" | tract == "52901")
view(fuquay)

#Subsetting for upper-middle class neighborhood (Cary)
cary <- wake_co |> subset(str_detect(tract_name, "Cary"))
view(cary)
```

```{r}
#Upward mobility in Wake County, Fuquay-Varina, and Cary
wake_upmobility <- mean(wake_co$kfr_pooled_pooled_p25, na.rm = TRUE)
fuquay_upmobility <- mean(fuquay$kfr_pooled_pooled_p25, na.rm = TRUE)
cary_upmobility <- mean(cary$kfr_pooled_pooled_p25, na.rm = TRUE)


abscomp <- data.frame(c("Wake County", "Fuquay-Varina Tracts", "Cary Tracts"),
                       c(wake_upmobility, fuquay_upmobility, cary_upmobility))
names(abscomp)[1] <- "Level"
names(abscomp)[2] <- "Absolute Mobility at the 25th Percentile"
abscomp

#College Degree attainment in Wake County, Fuquay, and Cary
wake_college <- mean(wake_co$frac_coll_plus2010, na.rm = TRUE)
fuquay_college <- mean(fuquay$frac_coll_plus2010, na.rm = TRUE)
cary_college <- mean(cary$frac_coll_plus2010, na.rm = TRUE)

#Median household income in Wake County, Fuquay, and Cary
wake_medinc <- mean(wake_co$med_hhinc2016, na.rm = TRUE)
fuquay_medinc <- mean(fuquay$med_hhinc2016, na.rm = TRUE)
cary_medinc <- mean(cary$med_hhinc2016, na.rm = TRUE)

#Poverty rate in Wake County, Fuquay, and Cary
wake_poor <- mean(wake_co$poor_share2010, na.rm = TRUE)
fuquay_poor <- mean(fuquay$poor_share2010, na.rm = TRUE)
cary_poor <- mean(cary$poor_share2010, na.rm = TRUE)

indicators <- data.frame(c("Wake County", "Fuquay-Varina Tracts", "Cary Tracts"),
                         c(wake_college, fuquay_college, cary_college),
                         c(wake_medinc, fuquay_medinc, cary_medinc),
                         c(wake_poor, fuquay_poor, cary_poor))

names(indicators)[1] <- "Region"
names(indicators)[2] <- "2010 College Degree Attainment Rate"
names(indicators)[3] <- "2016 Median Household Income"
names(indicators)[4] <- "2006-2010 Poverty Rate"

indicators

#White population share in Wake County, Fuquay, and Cary
wake_white <- mean(wake_co$share_white2010, na.rm = TRUE)
fuquay_white <- mean(fuquay$share_white2010, na.rm = TRUE)
cary_white <- mean(cary$share_white2010, na.rm = TRUE)

#Black population share in Wake County, Fuquay, and Cary
wake_black <- mean(wake_co$share_black2010, na.rm = TRUE)
fuquay_black <- mean(fuquay$share_black2010, na.rm = TRUE)
cary_black <- mean(cary$share_black2010, na.rm = TRUE)

#Hispanic population share in Wake County, Fuquay, and Cary
wake_hispanic <- mean(wake_co$share_hisp2010, na.rm = TRUE)
fuquay_hispanic <- mean(fuquay$share_hisp2010, na.rm = TRUE)
cary_hispanic <- mean(cary$share_hisp2010, na.rm = TRUE)

demos <- data.frame(c("Wake County", "Fuquay-Varina Tracts", "Cary Tracts"),
                         c(wake_white, fuquay_white, cary_white),
                         c(wake_black, fuquay_black, cary_black),
                         c(wake_hispanic, fuquay_hispanic, cary_hispanic))

names(demos)[1] <- "Region"
names(demos)[2] <- "2010 White Population Share"
names(demos)[3] <- "2010 Black Population Share"
names(demos)[4] <- "2010 Hispanic Population Share"

demos

```


```{r}

#Descriptive relationships between present-day statistics and upward mobility in Wake County 
#Creating custom columns for graphs
fuquay <- fuquay %>% mutate(neighborhood = "A")
cary <- cary %>% mutate(neighborhood = "B")

#Combine the datasets
combined_data <- rbind(fuquay, cary)
view(combined_data)

#White share of population
white <- wake_co |> 
        ggplot(aes(x = share_white2010, y = kfr_pooled_pooled_p25)) +
           geom_point(aes(x = share_white2010, y = kfr_pooled_pooled_p25)) +
           geom_point(data = combined_data,
             aes(color = neighborhood)) +
          geom_point(data = fuquay, aes(x = share_white2010, y = kfr_pooled_pooled_p25),
                      color = "#A31F34", size = 2) +
           geom_point(data = cary, aes(x = share_white2010, y = kfr_pooled_pooled_p25),
                      color = "#21908CFF", size = 2) +
          scale_color_manual(name = "Neighborhood", 
                     values = c("A" = "#A31F34", "B" =  "#21908CFF"),  
                     labels = c("Fuquay-Varina", "Cary")) +  
           geom_smooth(method = "lm", se = F) +
           labs(x = "White share of pop in 2010",
                y = "Absolute Mobility at the 25th percentile",
                title = "White population and upward mobility") +
          theme_minimal() +
          theme(legend.position = "bottom") 
white
ggsave("currentwhite.png")

#Black share of population 
black <- wake_co |> 
        ggplot(aes(x = share_black2010, y = kfr_pooled_pooled_p25)) +
           geom_point(aes(x = share_black2010, y = kfr_pooled_pooled_p25)) +
    geom_point(data = combined_data,
             aes(color = neighborhood)) +
          geom_point(data = fuquay, aes(x = share_black2010, y = kfr_pooled_pooled_p25),
                      color = "#A31F34", size = 2) +
           geom_point(data = cary, aes(x = share_black2010, y = kfr_pooled_pooled_p25),
                      color = "#21908CFF", size = 2) +
          scale_color_manual(name = "Neighborhood", 
                     values = c("A" = "#A31F34", "B" =  "#21908CFF"),  
                     labels = c("Fuquay-Varina", "Cary")) +  
           geom_smooth(method = "lm", se = F) +
           labs(x = "Black share of pop in 2010",
                y = "Absolute Mobility at the 25th percentile",
                title = "Black population and upward mobility") +
          theme_minimal() +
          theme(legend.position = "bottom") 
black
ggsave("currentblack.png")

#Hispanic share of population
hisp <- wake_co |> 
        ggplot(aes(x = share_hisp2010, y = kfr_pooled_pooled_p25)) +
           geom_point(aes(x = share_hisp2010, y = kfr_pooled_pooled_p25)) +
          geom_point(data = combined_data,
             aes(color = neighborhood)) +
          geom_point(data = fuquay, aes(x = share_hisp2010, y = kfr_pooled_pooled_p25),
                      color = "#A31F34", size = 2) +
           geom_point(data = cary, aes(x = share_hisp2010, y = kfr_pooled_pooled_p25),
                      color = "#21908CFF", size = 2) +
          scale_color_manual(name = "Neighborhood", 
                     values = c("A" = "#A31F34", "B" =  "#21908CFF"),  
                     labels = c("Fuquay-Varina", "Cary")) + 
           geom_smooth(method = "lm", se = F) +
           labs(x = "Hispanic share of pop in 2010",
                y = "Absolute Mobility at the 25th percentile",
                title = "Hispanic population and upward mobility") +
          theme_minimal() +
          theme(legend.position = "bottom") 
hisp
ggsave("currenthisp.png")

#College attainment
college <- wake_co |> 
        ggplot(aes(x = frac_coll_plus2010, y = kfr_pooled_pooled_p25)) +
           geom_point(aes(x = frac_coll_plus2010, y = kfr_pooled_pooled_p25)) +
    geom_point(data = combined_data,
             aes(color = neighborhood)) +
          geom_point(data = fuquay, aes(x = frac_coll_plus2010, y = kfr_pooled_pooled_p25),
                      color = "#A31F34", size = 2) +
           geom_point(data = cary, aes(x = frac_coll_plus2010, y = kfr_pooled_pooled_p25),
                      color = "#21908CFF", size = 2) +
          scale_color_manual(name = "Neighborhood", 
                     values = c("A" = "#A31F34", "B" =  "#21908CFF"),  
                     labels = c("Fuquay-Varina", "Cary")) + 
           geom_smooth(method = "lm", se = F) +
           labs(x = "Fraction of residents with a college degree or more",
                y = "Absolute Mobility at the 25th percentile",
                title = "Higher education attainment and upward mobility") +
          theme_minimal() +
          theme(legend.position = "bottom") 
college
ggsave("currentcol.png")


#Median household income
medincome <- wake_co |> 
        ggplot(aes(x = med_hhinc2016, y = kfr_pooled_pooled_p25)) +
           geom_point(aes(x = med_hhinc2016, y = kfr_pooled_pooled_p25)) +
           geom_point(data = combined_data,
             aes(color = neighborhood)) +
          geom_point(data = fuquay, aes(x = med_hhinc2016, y = kfr_pooled_pooled_p25),
                      color = "#A31F34", size = 2) +
           geom_point(data = cary, aes(x = med_hhinc2016, y = kfr_pooled_pooled_p25),
                      color = "#21908CFF", size = 2) +
          scale_color_manual(name = "Neighborhood", 
                     values = c("A" = "#A31F34", "B" =  "#21908CFF"),  
                     labels = c("Fuquay-Varina", "Cary")) + 
           geom_smooth(method = "lm", se = F) +
           labs(x = "Median household income in 2016",
                y = "Absolute Mobility at the 25th percentile",
                title = "Median household income and upward mobility") +
          scale_x_continuous(labels = scales::dollar_format()) +
          theme_minimal() +
          theme(legend.position = "bottom") 
medincome
ggsave("currentmedinc.png")

#Poverty rate
poverty <- wake_co |> 
        ggplot(aes(x = poor_share2010, y = kfr_pooled_pooled_p25)) +
           geom_point(aes(x = poor_share2010, y = kfr_pooled_pooled_p25)) +
           geom_point(data = combined_data,
             aes(color = neighborhood)) +
          geom_point(data = fuquay, aes(x = poor_share2010, y = kfr_pooled_pooled_p25),
                      color = "#A31F34", size = 2) +
           geom_point(data = cary, aes(x = poor_share2010, y = kfr_pooled_pooled_p25),
                      color = "#21908CFF", size = 2) +
          scale_color_manual(name = "Neighborhood", 
                     values = c("A" = "#A31F34", "B" =  "#21908CFF"),  
                     labels = c("Fuquay-Varina", "Cary")) + 
           geom_smooth(method = "lm", se = F) +
           labs(x = "Poverty rate in 2010",
                y = "Absolute Mobility at the 25th percentile",
                title = "Poverty rate and upward mobility") +
          theme_minimal() +
          theme(legend.position = "bottom") 
poverty
ggsave("currentpoverty.png")

#Single parent share
singleparent <- wake_co |> 
        ggplot(aes(x = singleparent_share2010, y = kfr_pooled_pooled_p25)) +
           geom_point(aes(x = singleparent_share2010, y = kfr_pooled_pooled_p25)) +
           geom_point(data = combined_data,
             aes(color = neighborhood)) +
          geom_point(data = fuquay, aes(x = singleparent_share2010, y = kfr_pooled_pooled_p25),
                      color = "#A31F34", size = 2) +
           geom_point(data = cary, aes(x = singleparent_share2010, y = kfr_pooled_pooled_p25),
                      color = "#21908CFF", size = 2) +
          scale_color_manual(name = "Neighborhood", 
                     values = c("A" = "#A31F34", "B" =  "#21908CFF"),  
                     labels = c("Fuquay-Varina", "Cary")) + 
           geom_smooth(method = "lm", se = F) +
           labs(x = "Single parent household share in 2010",
                y = "Absolute Mobility at the 25th percentile",
                title = "Single parenthood and upward mobility") +
          theme_minimal() +
          theme(legend.position = "bottom") 
singleparent
ggsave("currentsingle.png")

#Incarceration Rate for low-income children
jailall <- wake_co |> 
        ggplot(aes(x = jail_pooled_pooled_p25, y = kfr_pooled_pooled_p25)) +
           geom_point(aes(x = jail_pooled_pooled_p25, y = kfr_pooled_pooled_p25)) +
           geom_point(data = combined_data,
             aes(color = neighborhood)) +
          geom_point(data = fuquay, aes(x = jail_pooled_pooled_p25, y = kfr_pooled_pooled_p25),
                      color = "#A31F34", size = 2) +
           geom_point(data = cary, aes(x = jail_pooled_pooled_p25, y = kfr_pooled_pooled_p25),
                      color = "#21908CFF", size = 2) +
          scale_color_manual(name = "Neighborhood", 
                     values = c("A" = "#A31F34", "B" =  "#21908CFF"),  
                     labels = c("Fuquay-Varina", "Cary")) + 
           geom_smooth(method = "lm", se = F) +
           labs(x = "Share of low-income children incarcerated in 2010",
                y = "Absolute Mobility at the 25th percentile",
                title = "Incarceration rate and upward mobility") +
          theme_minimal() +
          theme(legend.position = "bottom") 
jailall
ggsave("currentjail.png")


```


```{r}

#Correlation coefficient table between present-day statistics and upward mobility

#Derive correlation coefficients 
white_wake <- cor(wake_co$kfr_pooled_pooled_p25, wake_co$share_white2010, use = "complete.obs")
white_fuquay <- cor(fuquay$kfr_pooled_pooled_p25, fuquay$share_white2010, use = "complete.obs")
white_cary <- cor(cary$kfr_pooled_pooled_p25, cary$share_white2010, use = "complete.obs")

black_wake <- cor(wake_co$kfr_pooled_pooled_p25, wake_co$share_black2010, use = "complete.obs")
black_fuquay <- cor(fuquay$kfr_pooled_pooled_p25, fuquay$share_black2010, use = "complete.obs")
black_cary <- cor(cary$kfr_pooled_pooled_p25, cary$share_black2010, use = "complete.obs")

hisp_wake <- cor(wake_co$kfr_pooled_pooled_p25, wake_co$share_hisp2010, use = "complete.obs")
hisp_fuquay <- cor(fuquay$kfr_pooled_pooled_p25, fuquay$share_hisp2010, use = "complete.obs")
hisp_cary <- cor(cary$kfr_pooled_pooled_p25, cary$share_hisp2010, use = "complete.obs")

col_wake <- cor(wake_co$kfr_pooled_pooled_p25, wake_co$frac_coll_plus2010, use = "complete.obs")
col_fuquay <- cor(fuquay$kfr_pooled_pooled_p25, fuquay$frac_coll_plus2010, use = "complete.obs")
col_cary <- cor(cary$kfr_pooled_pooled_p25, cary$frac_coll_plus2010, use = "complete.obs")

medinc_wake <- cor(wake_co$kfr_pooled_pooled_p25, wake_co$med_hhinc2016, use = "complete.obs")
medinc_fuquay <- cor(fuquay$kfr_pooled_pooled_p25, fuquay$med_hhinc2016, use = "complete.obs")
medinc_cary <- cor(cary$kfr_pooled_pooled_p25, cary$med_hhinc2016, use = "complete.obs")

poor_wake <- cor(wake_co$kfr_pooled_pooled_p25, wake_co$poor_share2010, use = "complete.obs")
poor_fuquay <- cor(fuquay$kfr_pooled_pooled_p25, fuquay$poor_share2010, use = "complete.obs")
poor_cary <- cor(cary$kfr_pooled_pooled_p25, cary$poor_share2010, use = "complete.obs")

single_wake <- cor(wake_co$kfr_pooled_pooled_p25, wake_co$singleparent_share2010, use = "complete.obs")
single_fuquay <- cor(fuquay$kfr_pooled_pooled_p25, fuquay$singleparent_share2010, use = "complete.obs")
single_cary <- cor(cary$kfr_pooled_pooled_p25, cary$singleparent_share2010, use = "complete.obs")

jail_wake <- cor(wake_co$kfr_pooled_pooled_p25, wake_co$jail_pooled_pooled_p25, use = "complete.obs")
jail_fuquay <- cor(fuquay$kfr_pooled_pooled_p25, fuquay$jail_pooled_pooled_p25, use = "complete.obs")
jail_cary <- cor(cary$kfr_pooled_pooled_p25, cary$jail_pooled_pooled_p25, use = "complete.obs")

#Create correlation coefficient dataframe 
coefcomp <- data.frame(c("White Population Share", "White Population Share", "White Population Share",
                         "Black Population Share", "Black Population Share", "Black Population Share",
                         "Hispanic Population Share", "Hispanic Population Share", "Hispanic Population Share", 
                         "College Educated Population", "College Educated Population", "College Educated Population",
                         "Median Household Income", "Median Household Income", "Median Household Income",
                         "Poverty Rate", "Poverty Rate", "Poverty Rate",
                         "Single Parent Share", "Single Parent Share", "Single Parent Share",
                         "Low-Income Child Incarceration Rate", "Low-Income Child Incarceration Rate", "Low-Income Child Incarceration Rate"),
                       c("Wake County", "Fuquay-Varina", "Cary",
                         "Wake County", "Fuquay-Varina", "Cary",
                         "Wake County", "Fuquay-Varina", "Cary",
                         "Wake County", "Fuquay-Varina", "Cary",
                         "Wake County", "Fuquay-Varina", "Cary",
                         "Wake County", "Fuquay-Varina", "Cary",
                         "Wake County", "Fuquay-Varina", "Cary",
                         "Wake County", "Fuquay-Varina", "Cary"),
                       c(white_wake , white_fuquay, white_cary,
                         black_wake, black_fuquay, black_cary,
                         hisp_wake, hisp_fuquay, hisp_cary,
                         col_wake, col_fuquay, col_cary,
                         medinc_wake, medinc_fuquay, medinc_cary,
                         poor_wake, poor_fuquay, poor_cary,
                         single_wake, single_fuquay, single_cary,
                         jail_wake, jail_fuquay, jail_cary))
                       
#Name columns 
names(coefcomp)[1] <- "Covariate"
names(coefcomp)[2] <- "Region"
names(coefcomp)[3] <- "Correlation Coefficient" 

#check 
coefcomp

#create table 
table_presentday <- coefcomp |> 
                    kable("html",
                          caption = "Correlations Between Present Day Demographic Variables and Upward Mobility",
                          align = "lcr",
                          col.names = c("Covariate", "Region", "Correlation Coefficient")) |> 
                    kable_styling("striped",  # Table style: "striped", "bordered", "hover", "condensed", "responsive", "basic"
                   full_width = FALSE) |> 
                   save_kable(file = "presentday.png", 
                              zoom = 1)
#check 
table_presentday

```


```{r}
#Historical covariates and their causal relationship to upward mobility

#White share of population
white2000 <- wake_co |> 
        ggplot(aes(x = share_white2000, y = kfr_pooled_pooled_p25)) +
           geom_point(aes(x = share_white2000, y = kfr_pooled_pooled_p25)) +
           geom_point(data = combined_data,
             aes(color = neighborhood)) +
          geom_point(data = fuquay, aes(x = share_white2000, y = kfr_pooled_pooled_p25),
                      color = "#A31F34", size = 2) +
           geom_point(data = cary, aes(x = share_white2000, y = kfr_pooled_pooled_p25),
                      color = "#21908CFF", size = 2) +
          scale_color_manual(name = "Neighborhood", 
                     values = c("A" = "#A31F34", "B" =  "#21908CFF"),  
                     labels = c("Fuquay-Varina", "Cary")) +  
           geom_smooth(method = "lm", se = F) +
           labs(x = "White share of pop in 2000",
                y = "Absolute Mobility at the 25th percentile",
                title = "Past White population and upward mobility") +
          theme_minimal() +
          theme(legend.position = "bottom") 
white2000
ggsave("2000white.png")


#Black share of population 
black2000 <- wake_co |> 
        ggplot(aes(x = share_black2000, y = kfr_pooled_pooled_p25)) +
           geom_point(aes(x = share_black2000, y = kfr_pooled_pooled_p25)) +
    geom_point(data = combined_data,
             aes(color = neighborhood)) +
          geom_point(data = fuquay, aes(x = share_black2000, y = kfr_pooled_pooled_p25),
                      color = "#A31F34", size = 2) +
           geom_point(data = cary, aes(x = share_black2000, y = kfr_pooled_pooled_p25),
                      color = "#21908CFF", size = 2) +
          scale_color_manual(name = "Neighborhood", 
                     values = c("A" = "#A31F34", "B" =  "#21908CFF"),  
                     labels = c("Fuquay-Varina", "Cary")) +  
           geom_smooth(method = "lm", se = F) +
           labs(x = "Black share of pop in 2000",
                y = "Absolute Mobility at the 25th percentile",
                title = "Past Black population and upward mobility") +
          theme_minimal() +
          theme(legend.position = "bottom") 
black2000
ggsave("2000black.png")

#Hispanic share of population
hisp2000 <- wake_co |> 
        ggplot(aes(x = share_hisp2000, y = kfr_pooled_pooled_p25)) +
           geom_point(aes(x = share_hisp2000, y = kfr_pooled_pooled_p25)) +
          geom_point(data = combined_data,
             aes(color = neighborhood)) +
          geom_point(data = fuquay, aes(x = share_hisp2000, y = kfr_pooled_pooled_p25),
                      color = "#A31F34", size = 2) +
           geom_point(data = cary, aes(x = share_hisp2000, y = kfr_pooled_pooled_p25),
                      color = "#21908CFF", size = 2) +
          scale_color_manual(name = "Neighborhood", 
                     values = c("A" = "#A31F34", "B" =  "#21908CFF"),  
                     labels = c("Fuquay-Varina", "Cary")) + 
           geom_smooth(method = "lm", se = F) +
           labs(x = "Hispanic share of pop in 2000",
                y = "Absolute Mobility at the 25th percentile",
                title = "Past hispanic population and upward mobility") +
          theme_minimal() +
          theme(legend.position = "bottom") 
hisp2000
ggsave("2000hisp.png")

#College attainment
college2000 <- wake_co |> 
        ggplot(aes(x = frac_coll_plus2000, y = kfr_pooled_pooled_p25)) +
           geom_point(aes(x = frac_coll_plus2000, y = kfr_pooled_pooled_p25)) +
    geom_point(data = combined_data,
             aes(color = neighborhood)) +
          geom_point(data = fuquay, aes(x = frac_coll_plus2000, y = kfr_pooled_pooled_p25),
                      color = "#A31F34", size = 2) +
           geom_point(data = cary, aes(x = frac_coll_plus2000, y = kfr_pooled_pooled_p25),
                      color = "#21908CFF", size = 2) +
          scale_color_manual(name = "Neighborhood", 
                     values = c("A" = "#A31F34", "B" =  "#21908CFF"),  
                     labels = c("Fuquay-Varina", "Cary")) + 
           geom_smooth(method = "lm", se = F) +
           labs(x = "Fraction of residents with a college degree or more",
                y = "Absolute Mobility at the 25th percentile",
                title = "Past higher education attainment and upward mobility") +
          theme_minimal() +
          theme(legend.position = "bottom") 
college2000
ggsave("2000col.png")


#Median household income
med1990 <- wake_co |> 
        ggplot(aes(x = med_hhinc1990, y = kfr_pooled_pooled_p25)) +
           geom_point(aes(x = med_hhinc1990, y = kfr_pooled_pooled_p25)) +
           geom_point(data = combined_data,
             aes(color = neighborhood)) +
          geom_point(data = fuquay, aes(x = med_hhinc1990, y = kfr_pooled_pooled_p25),
                      color = "#A31F34", size = 2) +
           geom_point(data = cary, aes(x = med_hhinc1990, y = kfr_pooled_pooled_p25),
                      color = "#21908CFF", size = 2) +
          scale_color_manual(name = "Neighborhood", 
                     values = c("A" = "#A31F34", "B" =  "#21908CFF"),  
                     labels = c("Fuquay-Varina", "Cary")) + 
           geom_smooth(method = "lm", se = F) +
           labs(x = "Median household income in 1990",
                y = "Absolute Mobility at the 25th percentile",
                title = "Past median household income and upward mobility") +
          scale_x_continuous(labels = scales::dollar_format()) +
          theme_minimal() +
          theme(legend.position = "bottom") 
med1990
ggsave("1990medinc.png")

#Poverty rate
poverty1990 <- wake_co |> 
        ggplot(aes(x = poor_share1990, y = kfr_pooled_pooled_p25)) +
           geom_point(aes(x = poor_share1990, y = kfr_pooled_pooled_p25)) +
           geom_point(data = combined_data,
             aes(color = neighborhood)) +
          geom_point(data = fuquay, aes(x = poor_share1990, y = kfr_pooled_pooled_p25),
                      color = "#A31F34", size = 2) +
           geom_point(data = cary, aes(x = poor_share1990, y = kfr_pooled_pooled_p25),
                      color = "#21908CFF", size = 2) +
          scale_color_manual(name = "Neighborhood", 
                     values = c("A" = "#A31F34", "B" =  "#21908CFF"),  
                     labels = c("Fuquay-Varina", "Cary")) + 
           geom_smooth(method = "lm", se = F) +
           labs(x = "Poverty rate in 1990",
                y = "Absolute Mobility at the 25th percentile",
                title = "Past poverty rate and upward mobility") +
          theme_minimal() +
          theme(legend.position = "bottom") 
poverty1990
ggsave("1990poverty.png")

#Single parent share
singleparent1990 <- wake_co |> 
        ggplot(aes(x = singleparent_share1990, y = kfr_pooled_pooled_p25)) +
           geom_point(aes(x = singleparent_share1990, y = kfr_pooled_pooled_p25)) +
           geom_point(data = combined_data,
             aes(color = neighborhood)) +
          geom_point(data = fuquay, aes(x = singleparent_share1990, y = kfr_pooled_pooled_p25),
                      color = "#A31F34", size = 2) +
           geom_point(data = cary, aes(x = singleparent_share1990, y = kfr_pooled_pooled_p25),
                      color = "#21908CFF", size = 2) +
          scale_color_manual(name = "Neighborhood", 
                     values = c("A" = "#A31F34", "B" =  "#21908CFF"),  
                     labels = c("Fuquay-Varina", "Cary")) + 
           geom_smooth(method = "lm", se = F) +
           labs(x = "Single parent household share in 1990",
                y = "Absolute Mobility at the 25th percentile",
                title = "Past single parenthood and upward mobility") +
          theme_minimal() +
          theme(legend.position = "bottom") 
singleparent1990
ggsave("1990single.png")

#Employment rate 
employ2000 <- wake_co |> 
        ggplot(aes(x = emp2000, y = kfr_pooled_pooled_p25)) +
           geom_point(aes(x = emp2000, y = kfr_pooled_pooled_p25)) +
           geom_point(data = combined_data,
             aes(color = neighborhood)) +
          geom_point(data = fuquay, aes(x = emp2000, y = kfr_pooled_pooled_p25),
                      color = "#A31F34", size = 2) +
           geom_point(data = cary, aes(x = emp2000, y = kfr_pooled_pooled_p25),
                      color = "#21908CFF", size = 2) +
          scale_color_manual(name = "Neighborhood", 
                     values = c("A" = "#A31F34", "B" =  "#21908CFF"),  
                     labels = c("Fuquay-Varina", "Cary")) + 
           geom_smooth(method = "lm", se = F) +
           labs(x = "Employment rate in 2000",
                y = "Absolute Mobility at the 25th percentile",
                title = "Past employment rate and upward mobility") +
          theme_minimal() +
          theme(legend.position = "bottom") 
employ2000
ggsave("employ2000.png")

#Population density
popden2000 <- wake_co |> 
        ggplot(aes(x = popdensity2000, y = kfr_pooled_pooled_p25)) +
           geom_point(aes(x = popdensity2000, y = kfr_pooled_pooled_p25)) +
           geom_point(data = combined_data,
             aes(color = neighborhood)) +
          geom_point(data = fuquay, aes(x = popdensity2000, y = kfr_pooled_pooled_p25),
                      color = "#A31F34", size = 2) +
           geom_point(data = cary, aes(x = popdensity2000, y = kfr_pooled_pooled_p25),
                      color = "#21908CFF", size = 2) +
          scale_color_manual(name = "Neighborhood", 
                     values = c("A" = "#A31F34", "B" =  "#21908CFF"),  
                     labels = c("Fuquay-Varina", "Cary")) + 
           geom_smooth(method = "lm", se = F) +
           labs(x = "Population density in 2000",
                y = "Absolute Mobility at the 25th percentile",
                title = "Past population density and upward mobility") +
          theme_minimal() +
          theme(legend.position = "bottom") 
popden2000
ggsave("popden2000.png")

```

```{r}

#Correlation coefficient table between historical covariates and upward mobility

#Derive correlation coefficients 
white_wake2000 <- cor(wake_co$kfr_pooled_pooled_p25, wake_co$share_white2000, use = "complete.obs")
white_fuquay2000 <- cor(fuquay$kfr_pooled_pooled_p25, fuquay$share_white2000, use = "complete.obs")
white_cary2000 <- cor(cary$kfr_pooled_pooled_p25, cary$share_white2000, use = "complete.obs")

black_wake2000 <- cor(wake_co$kfr_pooled_pooled_p25, wake_co$share_black2000, use = "complete.obs")
black_fuquay2000 <- cor(fuquay$kfr_pooled_pooled_p25, fuquay$share_black2000, use = "complete.obs")
black_cary2000 <- cor(cary$kfr_pooled_pooled_p25, cary$share_black2000, use = "complete.obs")

hisp_wake2000 <- cor(wake_co$kfr_pooled_pooled_p25, wake_co$share_hisp2000, use = "complete.obs")
hisp_fuquay2000 <- cor(fuquay$kfr_pooled_pooled_p25, fuquay$share_hisp2000, use = "complete.obs")
hisp_cary2000 <- cor(cary$kfr_pooled_pooled_p25, cary$share_hisp2000, use = "complete.obs")

col_wake2000 <- cor(wake_co$kfr_pooled_pooled_p25, wake_co$frac_coll_plus2000, use = "complete.obs")
col_fuquay2000 <- cor(fuquay$kfr_pooled_pooled_p25, fuquay$frac_coll_plus2000, use = "complete.obs")
col_cary2000 <- cor(cary$kfr_pooled_pooled_p25, cary$frac_coll_plus2000, use = "complete.obs")

medinc_wake1990 <- cor(wake_co$kfr_pooled_pooled_p25, wake_co$med_hhinc1990, use = "complete.obs")
medinc_fuquay1990 <- cor(fuquay$kfr_pooled_pooled_p25, fuquay$med_hhinc1990, use = "complete.obs")
medinc_cary1990 <- cor(cary$kfr_pooled_pooled_p25, cary$med_hhinc1990, use = "complete.obs")

poor_wake1990 <- cor(wake_co$kfr_pooled_pooled_p25, wake_co$poor_share1990, use = "complete.obs")
poor_fuquay1990 <- cor(fuquay$kfr_pooled_pooled_p25, fuquay$poor_share1990, use = "complete.obs")
poor_cary1990 <- cor(cary$kfr_pooled_pooled_p25, cary$poor_share1990, use = "complete.obs")

single_wake1990 <- cor(wake_co$kfr_pooled_pooled_p25, wake_co$singleparent_share1990, use = "complete.obs")
single_fuquay1990 <- cor(fuquay$kfr_pooled_pooled_p25, fuquay$singleparent_share1990, use = "complete.obs")
single_cary1990 <- cor(cary$kfr_pooled_pooled_p25, cary$singleparent_share1990, use = "complete.obs")

emp_wake <- cor(wake_co$kfr_pooled_pooled_p25, wake_co$emp2000, use = "complete.obs")
emp_fuquay <- cor(fuquay$kfr_pooled_pooled_p25, fuquay$emp2000, use = "complete.obs")
emp_cary <- cor(cary$kfr_pooled_pooled_p25, cary$emp2000, use = "complete.obs")

popden_wake <- cor(wake_co$kfr_pooled_pooled_p25, wake_co$popdensity2000, use = "complete.obs")
popden_fuquay <- cor(fuquay$kfr_pooled_pooled_p25, fuquay$popdensity2000, use = "complete.obs")
popden_cary <- cor(cary$kfr_pooled_pooled_p25, cary$popdensity2000, use = "complete.obs")

#Create correlation coefficient dataframe 
coefcomp_historic <- data.frame(c("2000 White Population Share", "2000 White Population Share", "2000 White Population Share",
                         "2000 Black Population Share", "2000 Black Population Share", "2000 Black Population Share",
                         "2000 Hispanic Population Share", "2000 Hispanic Population Share", "2000 Hispanic Population Share", 
                         "2000 College Educated Population", "2000 College Educated Population", "2000 College Educated Population",
                         "1990 Median Household Income", "1990 Median Household Income", "1990 Median Household Income",
                         "1990 Poverty Rate", "1990 Poverty Rate", "1990 Poverty Rate",
                         "1990 Single Parent Share", "1990 Single Parent Share", "1990 Single Parent Share",
                         "2000 Employment Rate", "2000 Employment Rate", "2000 Employment Rate",
                         "2000 Pop. Density", "2000 Pop. Density", "2000 Pop. Density"),
                       c("Wake County", "Fuquay-Varina", "Cary",
                         "Wake County", "Fuquay-Varina", "Cary",
                         "Wake County", "Fuquay-Varina", "Cary",
                         "Wake County", "Fuquay-Varina", "Cary",
                         "Wake County", "Fuquay-Varina", "Cary",
                         "Wake County", "Fuquay-Varina", "Cary",
                         "Wake County", "Fuquay-Varina", "Cary",
                         "Wake County", "Fuquay-Varina", "Cary",
                         "Wake County", "Fuquay-Varina", "Cary"),
                       c(white_wake2000, white_fuquay2000, white_cary2000,
                         black_wake2000, black_fuquay2000, black_cary2000,
                         hisp_wake2000, hisp_fuquay2000, hisp_cary2000,
                         col_wake2000, col_fuquay2000, col_cary2000,
                         medinc_wake1990, medinc_fuquay1990, medinc_cary1990,
                         poor_wake1990, poor_fuquay1990, poor_cary1990,
                         single_wake1990, single_fuquay1990, single_cary1990,
                         emp_wake, emp_fuquay, emp_cary,
                         popden_wake, popden_fuquay, popden_cary))
                       
#Name columns 
names(coefcomp_historic)[1] <- "Covariate"
names(coefcomp_historic)[2] <- "Region"
names(coefcomp_historic)[3] <- "Correlation Coefficient" 

#check 
coefcomp_historic

#create table 
table_historic <- coefcomp_historic |> 
                    kable("html",
                          caption = "Correlations Between Historical Covariates and Upward Mobility",
                          align = "lcr",
                          col.names = c("Covariate", "Region", "Correlation Coefficient")) |> 
                    kable_styling("striped",  # Table style: "striped", "bordered", "hover", "condensed", "responsive", "basic"
                   full_width = FALSE) |> 
                   save_kable(file = "historic.png", 
                              zoom = 1)
#check 
table_historic





```

```{r}

#Multivariate regression of historical covariates and upward mobility

#Wake County model 1 
wakereg1 <- lm(kfr_pooled_pooled_p25 ~ share_white2000 + share_black2000 + share_hisp2000 +
                                             frac_coll_plus2000 + med_hhinc1990 + poor_share1990 +
                                             singleparent_share1990 + emp2000 + popdensity2000,
                                            data = wake_co)
summary(wakereg1)

#Model 2
wakereg2 <- lm(kfr_pooled_pooled_p25 ~ share_white2000 + share_black2000 + share_hisp2000 +
                                             frac_coll_plus2000,
                                            data = wake_co)
summary(wakereg2)

#Model 3
wakereg3 <- lm(kfr_pooled_pooled_p25 ~ share_white2000 + share_black2000 + share_hisp2000 +
                                            med_hhinc1990,
                                            data = wake_co)
summary(wakereg3)

#Model 4
wakereg4 <- lm(kfr_pooled_pooled_p25 ~ share_white2000 + share_black2000 + share_hisp2000 +
                                            poor_share1990,
                                            data = wake_co)
summary(wakereg4)

#Model 5
wakereg5 <- lm(kfr_pooled_pooled_p25 ~ share_white2000 + share_black2000 + share_hisp2000 +
                                            singleparent_share1990,
                                            data = wake_co)
summary(wakereg5)

#Model 6
wakereg6 <- lm(kfr_pooled_pooled_p25 ~ share_white2000 + share_black2000 + share_hisp2000 +
                                            emp2000,
                                            data = wake_co)
summary(wakereg6)

#Model 7
wakereg7 <- lm(kfr_pooled_pooled_p25 ~ share_white2000 + share_black2000 + share_hisp2000 +
                                            popdensity2000,
                                            data = wake_co)
summary(wakereg7)


#Fuquay-Varina tracts
fuquayreg <- lm(kfr_pooled_pooled_p25 ~ share_white2000 + share_black2000 + share_hisp2000 +
                                             frac_coll_plus2000 + med_hhinc1990 + poor_share1990 +
                                             singleparent_share1990 + emp2000 + popdensity2000,
                                            data = fuquay)
                       
summary(fuquayreg)

#Cary Tracts
caryreg <- lm(kfr_pooled_pooled_p25 ~ share_white2000 + share_black2000 + share_hisp2000 +
                                             frac_coll_plus2000 + med_hhinc1990 + poor_share1990 +
                                             singleparent_share1990 + emp2000 + popdensity2000,
                                            data = cary)
                       
summary(caryreg)

# Create a regression table using the stargazer() function
stargazer(wakereg1, wakereg2, wakereg3, wakereg4, wakereg5, wakereg6, wakereg7, type = "text",  # Change 'type' to "latex" or "html" for different output formats
          title = "Series of regressions on upward mobility in Wake County",
          align = TRUE,
          column.labels = c("Full Covariate Model", "Model 2", "Model 3", "Model 4", "Model 5", "Model 6", "Model 7"),
          covariate.labels = c("2000 White pop. share", "2000 Black pop. share", "2000 Hisp. pop. share",
                               "2000 College degree plus share", "1990 Median household income", "1990 poverty share",
                               "1990 Single parent share", "2000 Employment rate", "2000 Population density"),
          dep.var.caption = "Dependent variable: Absolute mobility at the 25th percentile",
          dep.var.labels.include = FALSE,
          digits = 2,
          intercept.bottom = TRUE,
          model.numbers = TRUE,
          no.space = TRUE,
          omit.stat = c("f", "ser"),
          single.row = TRUE)



```





